spring.application.name=rca-engine

server.port=8080
management.endpoints.web.exposure.include=health,info
#connection spring boot to postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/rca_engine
spring.datasource.username=rca_user
spring.datasource.password= rca_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true